/**
 * The sampler: instruments made from samples that are uploaded or generated by a provider (ElevenLabs).
 *
 *   model/    the project (samples, instruments, pads): pure and tested
 *   server/   provider list, request checks, key choice, rate limit and the ElevenLabs call: server only apart from providers.ts
 *   store/    where the project and audio persist (IndexedDB; the interface allows a cloud store later)
 *   sync.ts   registers the instruments in the sound engine
 *
 * Imports only the sound feature and the shared components. Never the looper, the creator or the guitar tools.
 */
export { default as SamplerApp } from "./SamplerApp";
export { default as SamplerSync } from "./SamplerSync";
