#!/bin/sh
# Rebuilds ../kernelsWasm.ts from kernels.c. Needs clang with the wasm32 target and wasm-ld. Run from this folder.
set -e
clang --target=wasm32 -msimd128 -O3 -ffreestanding -nostdlib -fno-builtin -Wl,--no-entry -Wl,--import-memory -Wl,--export-dynamic -Wl,--strip-all -o kernels.wasm kernels.c
node -e '
const fs = require("fs");
const b64 = fs.readFileSync("kernels.wasm").toString("base64");
const lines = b64.match(/.{1,100}/g).map((l) => "  \"" + l + "\"").join(" +\n");
fs.writeFileSync("../kernelsWasm.ts", "/** Generated by wasm/build.sh from wasm/kernels.c. Do not edit. */\nexport const KERNELS_WASM_BASE64 =\n" + lines + ";\n");
'
rm kernels.wasm
